# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CalorieCounter_Nutritionix' do
  
  use_frameworks!

  pod 'SkyFloatingLabelTextField', '~> 3.0'

end
